<?php
namespace Tests\Feature;

use App\Http\Livewire\PopularGame;
use Illuminate\Support\Facades\Http;
use Mockery\MockInterface;

trait MockService
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->instance(
            PopularGame::class,
            \Mockery::mock(PopularGame::class, function (MockInterface $mock) {
                $mock->shouldReceive('getCacheKey')->andReturn('test_popularGames');
            })
        );
        $this->instance(
            IGDBService::class,
            \Mockery::mock(IGDBService::class, function (MockInterface $mock) {
                $mock->shouldReceive('getToken')->andReturn('dummy_token');
            })
        );

        Http::fake([
            config('services.igdb.base_url') . 'games' => Http::response($this->getFakeReponse()),
        ]);
    }
}
