<?php

namespace Tests\Feature;

use App\IGDBService;
use Tests\TestCase;

class IGDBAPITest extends TestCase
{
    public mixed $service;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->service = app()->make(IGDBService::class);

    }


    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function test_can_get_game_from_igdb_api()
    {
        $result = $this->service->getPopularGame();
        self::assertTrue($result->count() > 0);

        $result->each(function ($game){
            $this->assertTrue(isset($game['name']));
            $this->assertTrue(isset($game['id']));
        });
    }
}
